//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relish.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Relish.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Recipes.
        /// </summary>
        internal static string FindRecipesBtn {
            get {
                return ResourceManager.GetString("FindRecipesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery List.
        /// </summary>
        internal static string GroceryListBtn {
            get {
                return ResourceManager.GetString("GroceryListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Ingredients_Quantity {
            get {
                return ResourceManager.GetString("Ingredients_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ingredients_Toolbar_Add {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Ingredients_Toolbar_Delete {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Ingredients_Toolbar_Done {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Ingredients_Toolbar_Edit {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string IngredientsBtn {
            get {
                return ResourceManager.GetString("IngredientsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredient name must not be blank..
        /// </summary>
        internal static string IngredientsPopup_BlankNameError {
            get {
                return ResourceManager.GetString("IngredientsPopup_BlankNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string IngredientsPopup_Category {
            get {
                return ResourceManager.GetString("IngredientsPopup_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ingredient already exists..
        /// </summary>
        internal static string IngredientsPopup_DuplicateIngredientError {
            get {
                return ResourceManager.GetString("IngredientsPopup_DuplicateIngredientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ingredient here....
        /// </summary>
        internal static string IngredientsPopup_EntryPlaceholder {
            get {
                return ResourceManager.GetString("IngredientsPopup_EntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a positive quantity value..
        /// </summary>
        internal static string IngredientsPopup_InvalidQuantityError {
            get {
                return ResourceManager.GetString("IngredientsPopup_InvalidQuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string IngredientsPopup_Quantity {
            get {
                return ResourceManager.GetString("IngredientsPopup_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        internal static string IngredientsPopup_Units {
            get {
                return ResourceManager.GetString("IngredientsPopup_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Prep.
        /// </summary>
        internal static string MealPrepBtn {
            get {
                return ResourceManager.GetString("MealPrepBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Book.
        /// </summary>
        internal static string RecipeBookBtn {
            get {
                return ResourceManager.GetString("RecipeBookBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery List.
        /// </summary>
        internal static string Title_GroceryList {
            get {
                return ResourceManager.GetString("Title_GroceryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Title_Ingredients {
            get {
                return ResourceManager.GetString("Title_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Plan.
        /// </summary>
        internal static string Title_MealPlan {
            get {
                return ResourceManager.GetString("Title_MealPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string Title_Recipes {
            get {
                return ResourceManager.GetString("Title_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Title_StartSearch {
            get {
                return ResourceManager.GetString("Title_StartSearch", resourceCulture);
            }
        }
    }
}
