//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relish.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Relish.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Delete_Btn {
            get {
                return ResourceManager.GetString("Delete_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook time must be a positive integer..
        /// </summary>
        internal static string Error_BadCookTime {
            get {
                return ResourceManager.GetString("Error_BadCookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep time must be a positive integer..
        /// </summary>
        internal static string Error_BadPrepTime {
            get {
                return ResourceManager.GetString("Error_BadPrepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify some ingredients to begin the search..
        /// </summary>
        internal static string Error_NoIngredients {
            get {
                return ResourceManager.GetString("Error_NoIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Time.
        /// </summary>
        internal static string Filter_CookTime {
            get {
                return ResourceManager.GetString("Filter_CookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisine Type.
        /// </summary>
        internal static string Filter_Cuisine {
            get {
                return ResourceManager.GetString("Filter_Cuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for specific ingredients.
        /// </summary>
        internal static string Filter_Ingredient {
            get {
                return ResourceManager.GetString("Filter_Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        internal static string Filter_Keyword {
            get {
                return ResourceManager.GetString("Filter_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Type.
        /// </summary>
        internal static string Filter_MealType {
            get {
                return ResourceManager.GetString("Filter_MealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one ingredient..
        /// </summary>
        internal static string Filter_MustSpecifyError {
            get {
                return ResourceManager.GetString("Filter_MustSpecifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preperation Style.
        /// </summary>
        internal static string Filter_PrepStyle {
            get {
                return ResourceManager.GetString("Filter_PrepStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep Time.
        /// </summary>
        internal static string Filter_PrepTime {
            get {
                return ResourceManager.GetString("Filter_PrepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter max time (mins):.
        /// </summary>
        internal static string Filter_TimeFilter_Label {
            get {
                return ResourceManager.GetString("Filter_TimeFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all ingredients?.
        /// </summary>
        internal static string Filter_UseAllIngredients {
            get {
                return ResourceManager.GetString("Filter_UseAllIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Recipes.
        /// </summary>
        internal static string Home_FindRecipesBtn {
            get {
                return ResourceManager.GetString("Home_FindRecipesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery List.
        /// </summary>
        internal static string Home_GroceryListBtn {
            get {
                return ResourceManager.GetString("Home_GroceryListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Home_IngredientsBtn {
            get {
                return ResourceManager.GetString("Home_IngredientsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Prep.
        /// </summary>
        internal static string Home_MealPrepBtn {
            get {
                return ResourceManager.GetString("Home_MealPrepBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Book.
        /// </summary>
        internal static string Home_RecipeBookBtn {
            get {
                return ResourceManager.GetString("Home_RecipeBookBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELISH.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Ingredients_Quantity {
            get {
                return ResourceManager.GetString("Ingredients_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ingredients_Toolbar_Add {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Ingredients_Toolbar_Done {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Ingredients_Toolbar_Edit {
            get {
                return ResourceManager.GetString("Ingredients_Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredient name must not be blank..
        /// </summary>
        internal static string IngredientsPopup_BlankNameError {
            get {
                return ResourceManager.GetString("IngredientsPopup_BlankNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string IngredientsPopup_Category {
            get {
                return ResourceManager.GetString("IngredientsPopup_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ingredient already exists..
        /// </summary>
        internal static string IngredientsPopup_DuplicateIngredientError {
            get {
                return ResourceManager.GetString("IngredientsPopup_DuplicateIngredientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ingredient here....
        /// </summary>
        internal static string IngredientsPopup_EntryPlaceholder {
            get {
                return ResourceManager.GetString("IngredientsPopup_EntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a positive quantity value..
        /// </summary>
        internal static string IngredientsPopup_InvalidQuantityError {
            get {
                return ResourceManager.GetString("IngredientsPopup_InvalidQuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string IngredientsPopup_Quantity {
            get {
                return ResourceManager.GetString("IngredientsPopup_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        internal static string IngredientsPopup_Units {
            get {
                return ResourceManager.GetString("IngredientsPopup_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved recipes..
        /// </summary>
        internal static string RecipeBook_NoSavedRecipes {
            get {
                return ResourceManager.GetString("RecipeBook_NoSavedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook time: {0} mins.
        /// </summary>
        internal static string RecipeList_CookTime {
            get {
                return ResourceManager.GetString("RecipeList_CookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe search failed..
        /// </summary>
        internal static string RecipeList_ErrorString {
            get {
                return ResourceManager.GetString("RecipeList_ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipes were found..
        /// </summary>
        internal static string RecipeList_NoRecipesFound {
            get {
                return ResourceManager.GetString("RecipeList_NoRecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved recipes..
        /// </summary>
        internal static string RecipeList_NoSavedRecipes {
            get {
                return ResourceManager.GetString("RecipeList_NoSavedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep time: {0} mins.
        /// </summary>
        internal static string RecipeList_PrepTime {
            get {
                return ResourceManager.GetString("RecipeList_PrepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Meal Prep.
        /// </summary>
        internal static string RecipeView_AddToMealPrep {
            get {
                return ResourceManager.GetString("RecipeView_AddToMealPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to recipe book.
        /// </summary>
        internal static string RecipeView_AddToRecipeBook {
            get {
                return ResourceManager.GetString("RecipeView_AddToRecipeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        internal static string RecipeView_Directions {
            get {
                return ResourceManager.GetString("RecipeView_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients:.
        /// </summary>
        internal static string RecipeView_Ingredients {
            get {
                return ResourceManager.GetString("RecipeView_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        internal static string RecipeView_OpenInBrowser {
            get {
                return ResourceManager.GetString("RecipeView_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from recipe book.
        /// </summary>
        internal static string RecipeView_RemoveFromRecipeBook {
            get {
                return ResourceManager.GetString("RecipeView_RemoveFromRecipeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servings.
        /// </summary>
        internal static string RecipeView_Servings {
            get {
                return ResourceManager.GetString("RecipeView_Servings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery List.
        /// </summary>
        internal static string Title_GroceryList {
            get {
                return ResourceManager.GetString("Title_GroceryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Title_Ingredients {
            get {
                return ResourceManager.GetString("Title_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Recipes.
        /// </summary>
        internal static string Title_RecipeBook {
            get {
                return ResourceManager.GetString("Title_RecipeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string Title_Results {
            get {
                return ResourceManager.GetString("Title_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Recipes.
        /// </summary>
        internal static string Title_StartSearch {
            get {
                return ResourceManager.GetString("Title_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium to use this feature!.
        /// </summary>
        internal static string UpgradePopup_Text {
            get {
                return ResourceManager.GetString("UpgradePopup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string UpgradePopup_UpgradeBtn {
            get {
                return ResourceManager.GetString("UpgradePopup_UpgradeBtn", resourceCulture);
            }
        }
    }
}
